var data0 = [
    {
        "src": "http://imgsrc.baidu.com/baike/abpic/item/bf096b63f6246b6053075d6be4f81a4c510fa2a0.jpg",
        "text": "《我和我的祖国》是由陈凯歌担任总导演，张一白、管虎、薛晓路、徐峥、宁浩、文牧野联合执导，（按出场顺序）黄渤、张译、吴京、杜江、葛优、刘昊然、陈飞宇、宋佳领衔主演的剧情片。该…",
        "title": "我和我的祖国",
        "id": "1"
    },
    {
        "src": "http://imgsrc.baidu.com/baike/abpic/item/f703738da97739121c7cfa79f7198618367ae254.jpg",
        "text": "《中国机长》（The Captain）是由刘伟强执导，于勇敢编剧，李锦文监制，张涵予、欧豪、杜江、袁泉、张天爱、李沁领衔主演，张雅玫、杨祺如、高戈主演的剧情传记灾难片。该片根据2018年5…",
        "title": "中国机长",
        "id": "2"
    },
    {
        "src": "http://imgsrc.baidu.com/baike/abpic/item/6159252dd42a28347e3bf97654b5c9ea15cebf2a.jpg",
        "text": "《南方车站的聚会》是由和力辰光国际文化传媒股份有限公司出品的剧情片，由刁亦男执导，胡歌、桂纶镁领衔主演，廖凡、万茜特别出演。该片于2019年5月18日在戛纳电影节首映，于2019…",
        "title": "南方车站的聚会",
        "id": "3"
    },
    {
        "src": "http://imgsrc.baidu.com/baike/abpic/item/03087bf40ad162d9d8b6bb111edfa9ec8a13cd67.jpg",
        "text": "《少年的你》是根据玖月晞小说改编的电影，由曾国祥执导，周冬雨、易烊千玺、尹昉、黄觉、吴越、周也、刘然、张耀、张艺凡、赵润南、郜玄铭主演。该片讲述在高考前夕，被一场校园意外改…",
        "title": "少年的你",
        "id": "4"
    },
    {
        "src": "http://imgsrc.baidu.com/baike/abpic/item/bf096b63f6246b6019eaa317e4f81a4c500fa2e8.jpg",
        "text": "《被光抓走的人》是由董润年编剧并执导，黄渤、王珞丹、谭卓、白客、黄璐、宋春丽、文淇领衔主演，丁溪鹤、李嘉琪、吕星辰主演，焦俊艳、李倩、李诞、王菊友情出演，黄觉特别出演的现实主义爱情电影。该片讲述…",
        "title": "被光抓走的人",
        "id": "5"
    },
    {
        "src": "http://imgsrc.baidu.com/baike/abpic/item/ac6eddc451da81cb38877b5f5966d0160924313a.jpg",
        "text": "《星球大战：最后的绝地武士》是《星球大战》系列第八部，是由美国卢卡斯电影有限公司出品的科幻动作片，由莱恩·约翰逊执导，黛茜·雷德利、约翰·波耶加、奥斯卡·伊萨克、亚当·德赖弗、马克·…",
        "title": "星球大战8",
        "id": "6"
    },
    {
        "src": "http://imgsrc.baidu.com/baike/abpic/item/2e2eb9389b504fc2a7b68177eadde71191ef6dd2.jpg",
        "text": "《冰雪奇缘2》是由克里斯·巴克、珍妮弗·李执导的动画电影，是2013年电影《冰雪奇缘》的续集，由克里斯汀·贝尔、伊迪娜·门泽尔等领衔配音。该片于2019年11月22日在北美和中国内地同步上映…",
        "title": "冰雪奇缘2",
        "id": "7"
    },
    {
        "src": "http://imgsrc.baidu.com/baike/abpic/item/bd315c6034a85edfa4a4ae1146540923dd5475d3.jpg",
        "text": "《小丑》是由托德·菲利普斯执导，杰昆·菲尼克斯、莎姬·贝兹、罗伯特·德尼罗、弗兰西丝·康罗伊、布莱特·卡伦等联袂出演的犯罪剧情片。2019年8月31日在威尼斯电影节主竞赛单元首映。《小丑》的…",
        "title": "小丑",
        "id": "8"
    },
    {
        "src": "http://imgsrc.baidu.com/baike/abpic/item/9213b07eca8065388d7d4a469bdda144ac3482d4.jpg",
        "text": "《勇敢者游戏：决战丛林》是由美国索尼哥伦比亚影片公司出品的动作冒险电影，由杰克·卡斯丹执导，道恩·强森、杰克·布莱克、凯文·哈特、凯伦·吉兰、尼克·乔纳斯、鲍比·坎纳瓦尔、瑟达瑞斯·…",
        "title": "勇敢者游戏：决战丛林",
        "id": "9"
    },
    {
        "src": "http://imgsrc.baidu.com/baike/abpic/item/b90e7bec54e736d102b1ed059b504fc2d5626918.jpg",
        "text": "在日本舰队3天徒劳的追逐期间截收到的大量电报是一个很大的收获。暴露给美国的不仅是山本联台舰队的每一艘军舰几乎郡已出海，而且这次大规模行动的目的也…",
        "title": "决战中途岛",
        "id": "10"
    }
]


var data1 = [
    {
        "src": "http://imgsrc.baidu.com/baike/abpic/item/03087bf40ad162d9c523b10019dfa9ec8b13cdd9.jpg",
        "text": "撒贝宁，1976年3月23日出生于广东湛江，籍贯湖北武汉，祖籍安徽和县。中央电视台节目主持人。1999年开始主持法制节目《今日说法》。2011年主持央视娱乐节…",
        "title": "撒贝宁",
        "id": "1"
    },
    {
        "src": "http://imgsrc.baidu.com/baike/abpic/item/aa18972bd40735fa2ae672dd93510fb30f2408bb.jpg",
        "text": "于朦胧（Alan Yu），1988年6月15日生于新疆乌鲁木齐，中国内地男演员、歌手、MV导演。2010年，担任丁爽歌曲《61秒》的MV导演。2013年，参加湖南卫视选秀娱乐节目《快乐男声》，获得全国总决赛…",
        "title": "于朦胧",
        "id": "2"
    },
    {
        "src": "http://imgsrc.baidu.com/baike/abpic/item/94cad1c8a786c9170848525fc63d70cf3bc75708.jpg",
        "text": "高以翔（Godfrey Tsao，1984年9月22日-2019年11月27日），原名曹志翔，出生于台湾省台北市，华语影视男演员、模特，毕业于卡普兰诺大学。2006年，出演个人首部电视剧《爱情魔发…",
        "title": "高以翔",
        "id": "3"
    },
    {
        "src": "http://imgsrc.baidu.com/baike/abpic/item/42166d224f4a20a4e26080069d529822730ed0f1.jpg",
        "text": "朱一龙，1988年4月16日出生于湖北武汉，中国内地男演员，毕业于北京电影学院2006级表演系本科。2009年出演首部电影《再生缘》，后参演多部《周末王刚讲故事》（又名：《儿女传奇》）系列数字…",
        "title": "朱一龙",
        "id": "4"
    },
    {
        "src": "http://imgsrc.baidu.com/baike/abpic/item/95eef01f3a292df5554b4d89b2315c6035a873a6.jpg",
        "text": "彦希，1996年2月17日出生于山东省，中国内地男演员、歌手。2016年，出演个人首部电视剧《明星志愿》，从而开始演艺生涯；5月，加盟古装电视剧《轩辕剑之汉之云》，剧中饰演徒…",
        "title": "彦希",
        "id": "5"
    },
    {
        "src": "http://imgsrc.baidu.com/baike/abpic/item/bba1cd11728b47108be04042cecec3fdfd032374.jpg",
        "text": "张若昀，1988年8月24日出生于北京市，中国内地男演员，毕业于北京电影学院。2004年，通过参演首部电视剧《海的誓言》而进入演艺圈。2011年，凭借励志革命剧《黑狐》中方天翼一角广受关注，并…",
        "title": "张若昀",
        "id": "6"
    },
    {
        "src": "http://imgsrc.baidu.com/baike/abpic/item/3b87e950352ac65c4445ae15f4f2b21193138a10.jpg",
        "text": "李沁，1990年9月27日出生于江苏省苏州市，中国内地影视女演员。2008年，李沁因在李少红版《红楼梦》中饰演少年薛宝钗而被观众熟知。2010年，李沁凭借在建党九十周年献礼片《建党伟…",
        "title": "李沁",
        "id": "7"
    },
    {
        "src": "http://imgsrc.baidu.com/baike/abpic/item/38dbb6fd5266d0167927ca029b2bd40735fa35d9.jpg",
        "text": "周杰伦（Jay Chou），1979年1月18日出生于台湾省新北市，毕业于淡江中学，中国台湾流行乐男歌手、音乐人、演员、导演、编剧等。2000年发行首张个人专辑《Jay》。2001年发行的专辑《…",
        "title": "周杰伦",
        "id": "8"
    },
    {
        "src": "http://imgsrc.baidu.com/baike/abpic/item/c2fdfc039245d688bec3d0a2a9c27d1ed31b24f6.jpg",
        "text": "刘维，1986年8月31日出生于辽宁鞍山，中国内地歌手、演员、主持人。2005年，刘维参加第二届莱卡我型我秀获得冠军。10月，获得全球华人新秀歌唱大赛冠军。2009年11月，参演电影《歌…",
        "title": "刘维",
        "id": "9"
    },
    {
        "src": "http://imgsrc.baidu.com/baike/abpic/item/8644ebf81a4c510ff75fc77f6f59252dd42aa53f.jpg",
        "text": "王一博（YiBo），1997年8月5日出生于中国河南省洛阳市，中国流行乐男歌手、演员、主持人，男子演唱组合UNIQ成员，职业摩托车赛车手。2014年9月15日，以UNIQ组合成员身份正式出道；12月…",
        "title": "王一博",
        "id": "10"
    }
]


var data1a = [{
    "id": "1",
    "title": "庆余年",
    "zhishu": "205186",
    "src": "http://imgsrc.baidu.com/baike/abpic/item/b3b7d0a20cf431ad9e3078594436acaf2fdd98eb.jpg",
    "text": "《庆余年》是由孙皓执导，张若昀、李沁、陈道明、吴刚、辛芷蕾、宋轶、郭麒麟等主演的古装剧。该剧改编自猫腻的同名小说，讲述了一个有着神秘身世的少年，自海边小城初出茅庐，历经家族、江…"
}, {
    "id": "2",
    "title": "剑王朝",
    "zhishu": "20033",
    "src": "http://imgsrc.baidu.com/baike/abpic/item/241f95cad1c8a7863a91c76b6809c93d70cf5018.jpg",
    "text": "《剑王朝》是由冯小刚监制，马华干执导，饶俊编剧，李现、李一桐、刘奕君、姚笛、赵圆瑗、何润东、肖旭、李光复等主演的古装武侠剧。该剧根据无罪同名小说改编，讲述了身份神秘的市井酒铺少年丁宁，历经…"
}, {
    "id": "3",
    "title": "心灵法医",
    "zhishu": "12200",
    "src": "http://imgsrc.baidu.com/baike/abpic/item/a2cc7cd98d1001e9e54bb173b70e7bec54e79753.jpg",
    "text": "《心灵法医》是由龚朝晖执导，聂远、宋轶、芦芳生领衔主演的都市悬疑推理剧。该剧根据法医朱明川的小说《听尸》改编，讲述了鹏海市法医明川破案无数，成为远近闻名的“听尸者”，却因“杀人医生”案被刑…"
}, {
    "id": "4",
    "title": "第二次也很美",
    "zhishu": "11571",
    "src": "http://imgsrc.baidu.com/baike/abpic/item/4b90f603738da9776ae61657bf51f8198718e385.jpg",
    "text": "《第二次也很美》是由陈铭章执导，王子文、张鲁一、于小伟、于明加主演的都市情感剧。该剧讲述了“二次元少女”安安，直面并战胜现实中的种种苦涩，终凭借自身努力成长为职场女性，实现…"
}, {
    "id": "5",
    "title": "天涯明月刀",
    "zhishu": "5600",
    "src": "http://imgsrc.baidu.com/baike/abpic/item/c8177f3e6709c93d93f5f7e0903df8dcd10054a6.jpg",
    "text": "《天涯明月刀》是改编自古龙小说的电视剧，由腾讯影业发行，导演是张黎，编剧是钱雁秋、刘伽茵，发行时间是2017年。"
}, {
    "id": "6",
    "title": "闪光少女",
    "zhishu": "5177",
    "src": "http://imgsrc.baidu.com/baike/abpic/item/9345d688d43f87945dfcb0ddd81b0ef41ad53ac6.jpg",
    "text": "《闪光少女》是由安乐影片有限公司出品发行的青春热血校园电影，由王冉执导，徐璐、彭昱畅领衔主演，骆明劼、刘泳希、韩忠羽、鲁照华、李诺、陈雨锶主演，陈奕迅、闫妮、耿乐特别演出。…"
}, {
    "id": "7",
    "title": "天龙八部",
    "zhishu": "4930",
    "src": "http://imgsrc.baidu.com/baike/abpic/item/d000baa1cd11728b6d8d2da0c0fcc3cec2fd2c8b.jpg",
    "text": "《天龙八部》是根据金庸同名小说改编的古装武侠剧，由张纪中担任总制片人，鞠觉亮、周晓文、于敏、赵箭联合执导，胡军、林志颖、高虎、刘亦菲、陈好、刘涛主演，于2003年12月11日在浙江…"
}, {
    "id": "8",
    "title": "如懿传",
    "zhishu": "3620",
    "src": "http://imgsrc.baidu.com/baike/abpic/item/5fdf8db1cb134954bc8303725b4e9258d1094a03.jpg",
    "text": "《如懿传》是由新丽传媒出品，由汪俊执导，流潋紫担任编剧，周迅、霍建华领衔主演，张钧甯、董洁、童瑶、辛芷蕾、李纯、何泓姗、邬君梅、胡可、经超、陈昊宇、曾一萱、曹曦文、张佳宁、…"
}, {
    "id": "9",
    "title": "从前有座灵剑山",
    "zhishu": "3510",
    "src": "http://imgsrc.baidu.com/baike/abpic/item/a50f4bfbfbedab6466dcf8bbf836afc379311e1a.jpg",
    "text": "《从前有座灵剑山》是由爱奇艺、腾讯影业、恒星引力传媒、ABB良品制造出品，万达影视新媒诚品、好看传媒、留白影视、娱跃文化联合出品，于中中执导，由许凯、张榕容、朱元冰、高雨儿、郭晓婷(特别主演)…"
}, {
    "id": "10",
    "title": "遇见王沥川",
    "zhishu": "3491",
    "src": "http://imgsrc.baidu.com/baike/abpic/item/d1160924ab18972b83b6b51befcd7b899f510a56.jpg",
    "text": "《遇见王沥川》改编自施定柔的小说《沥川往事》，由上海拓乐影视文化传媒有限公司承制出品，周恬制作，陈铭章执导，施定柔编剧，高以翔、焦俊艳、连凯、郑希怡、林佑威、王若心主演的治…"
}];

var data1b = [{
        "id": "1",
        "title": "潮流合伙人",
        "zhishu": "52623",
        "src": "http://imgsrc.baidu.com/baike/abpic/item/f7246b600c33874419e353755e0fd9f9d72aa091.jpg",
        "text": "《潮流合伙人》是由爱奇艺高级副总裁陈伟担任总监制，爱奇艺副总裁车澈担任总制片人的真人秀节目，于2019年12月6日播出。该节目由主理人吴亦凡，及潮流合伙人杨颖Angelababy、潘…"
    }, {
        "id": "2",
        "title": "吐槽大会",
        "zhishu": "23558",
        "src": "http://imgsrc.baidu.com/baike/abpic/item/bd3eb13533fa828bb2b72582f21f4134970a5a3e.jpg",
        "text": "《吐槽大会》是由腾讯视频、上海笑果文化传媒有限公司联合出品的喜剧脱口秀节目。每季均由张绍刚主持，前三季各10期。《吐槽大会》包括：《吐槽大会第一季…"
    }, {
        "id": "3",
        "title": "明星大侦探",
        "zhishu": "13530",
        "src": "http://imgsrc.baidu.com/baike/abpic/item/b58f8c5494eef01fd5f6b61aebfe9925bd317d0b.jpg",
        "text": "《明星大侦探》是芒果TV推出的系列明星推理真人秀节目。《明星大侦探》包括：《明星大侦探第一季》、《明星大侦探第二季》、《明星大侦探第三季》、《明星大侦探第四季》、《明星大侦探第五季》。《明星…"
    }, {
        "id": "4",
        "title": "演员请就位",
        "zhishu": "12926",
        "src": "http://imgsrc.baidu.com/baike/abpic/item/2f738bd4b31c8701127bd68c287f9e2f0608ff8f.jpg",
        "text": "《演员请就位》是腾讯视频出品的导演选角真人秀，共10期，由陈凯歌、李少红、赵薇、郭敬明四位导演担任导师，对演员的表演点评，然后选角进组。节目由沙溢担任演员工会会长，并与一起柳岩担任终极盛典主持…"
    }, {
        "id": "5",
        "title": "智慧树",
        "zhishu": "10315",
        "src": "http://imgsrc.baidu.com/baike/abpic/item/8326cffc1e178a82ceb936d1f903738da977e83e.jpg",
        "text": "中央电视台少儿频道《智慧树》栏目创办于2003年12月28日，是为3-6岁学龄前儿童专门打造的一档益智娱乐节目。节目以活泼生动的形式，寓科学的教育理念于生…"
    }, {
        "id": "6",
        "title": "主持人大赛",
        "zhishu": "9941",
        "src": "http://imgsrc.baidu.com/baike/abpic/item/241f95cad1c8a78681e11c7d6809c93d71cf50fd.jpg",
        "text": "CCTV电视节目主持人大赛是由中国中央电视台精心打造的一项重大赛事，自1988年，已经成功举办过六届。节目通过搭建优秀电视节目主持人才的国家级竞争平台，力求选拔出…"
    }, {
        "id": "7",
        "title": "快乐大本营",
        "zhishu": "7615",
        "src": "http://imgsrc.baidu.com/baike/abpic/item/e824b899a9014c0849f3f58d057b02087af4f4ca.jpg",
        "text": "《快乐大本营》是湖南卫视推出的嘉宾访谈游戏秀节目，由何炅、谢娜、李维嘉、吴昕、杜海涛五人担任主持。节目以游戏为主，辅以歌舞及各种形式节目。每期节…"
    }, {
        "id": "8",
        "title": "奇葩说第6季",
        "zhishu": "7484",
        "src": "http://imgsrc.baidu.com/baike/abpic/item/b7fd5266d016092498df0b6bdb0735fae7cd34c3.jpg",
        "text": "《奇葩说第六季》是由爱奇艺与米未联合出品的融入辩论元素的说话达人秀节目，由马东担任主持人。该季全面升级为四大导师带队比拼的形式，蔡康永、薛兆丰、李诞、罗振宇担任导师。2019年10月31日起，每周…"
}, {
    "id": "9",
    "title": "非诚勿扰",
    "zhishu": "4735",
    "src": "http://imgsrc.baidu.com/baike/abpic/item/1ad5ad6eddc451dab36da3d9bafd5266d016326c.jpg",
    "text": "《非诚勿扰》是江苏卫视制作的一档生活服务类节目，由孟非担任主持。节目中有24位单身女生以亮灭灯方式来决定报名男嘉宾的去留，经过“爱之初体验”、“爱…"
}, {
    "id": "10",
    "title": "嗨唱转起来",
    "zhishu": "4706",
    "src": "http://imgsrc.baidu.com/baike/abpic/item/dcc451da81cb39db3ba76c29df160924ab18306d.jpg",
    "text": "《嗨唱转起来》是由湖南卫视安德胜工作室和刘伟工作室联合制作的全民音乐综艺互动秀节目。该节目由谢娜和罗志祥组成嗨唱大玩家，召集各领域的音乐达人演唱具有时…"
}];

